import { Sora,Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import  Layouts  from './commons/components/Layouts'

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const sora = Sora({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
})

export const metadata = {
  title: "Reza | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light">
      <body
        className={sora.className}
      >
        <Providers>
          <Layouts>
            {children}
          </Layouts>
        </Providers>
      </body>
    </html>
  );
}
